name: CI

on: [ push, pull_request ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: "Run tests on Ubuntu"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update -qq -y && sudo apt-get install -qq -y wget curl shunit2
      - name: Run tests
        run: make test

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    name: "Run tests on Fedora"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: dnf update -q -y && dnf install -q -y make patch wget curl shunit2
      - name: Run tests
        run: make test

  opensuse:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed:latest
    name: "Run tests on OpenSUSE"
    steps:
      - name: Install dependencies
        run: zypper ref && zypper --non-interactive in tar gzip findutils make patch wget shunit2
      - uses: actions/checkout@v4
      - name: Run tests
        run: make test

  archlinux:
    runs-on: ubuntu-latest
    container: archlinux:latest
    name: "Run tests on ArchLinux"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman-key --init && \
          pacman -Syu --noconfirm && \
          pacman -Sy --noconfirm git base base-devel make patch wget curl && \
          useradd -d /home/makepkg makepkg && \
          mkdir -p /home/makepkg/{.config/pacman,.gnupg,out} && \
          chown -R makepkg:users /home/makepkg && \
          sudo -u makepkg /bin/bash -c "cd /home/makepkg && git clone --quiet --depth 1 https://aur.archlinux.org/shunit2.git && cd shunit2/ && makepkg" && \
          pacman -U --noconfirm /home/makepkg/shunit2/shunit2-*.pkg.tar.zst
      - name: Run tests
        run: make test

  macos:
    runs-on: macos-latest
    name: "Run tests on macOS"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install wget shunit2
      - name: Run tests
        run: make test

  freebsd:
    runs-on: ubuntu-latest
    name: "Run tests on FreeBSD"
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      id: freebsd
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        copyback: false
        prepare: |
          pkg install -y wget curl shunit2
        run: make test
